'change logic to scan images'

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -7,15 +7,28 @@ steps:
      - '-c'
      - |
        for i in $(gcloud artifacts docker images list us-docker.pkg.dev/$_MAIN_PROJECT_ID/gcr.io/ --format='value(package,version)' | awk  '{print $1 "@" $$NF}'); do gcloud artifacts docker images scan $i --location us --remote --format='value(response.scan)' >> /workspace/scan_id.txt; done
-   - id: severity check
+   - id: from to
      name: gcr.io/google.com/cloudsdktool/cloud-sdk
      entrypoint: bash
      waitFor: ['scan']
      args:
      - '-c'
      - |
-       for i in $(cat /workspace/scan_id.txt); do gcloud artifacts docker images list-vulnerabilities $i --location us \
-       --format='value(vulnerability.effectiveSeverity)'| if grep -Fxq $_SEVERITY; then echo 'Failed vulnerability check' $$i && exit 1; else echo 'Passed with success on vulnerability check' $$i && exit 0; fi;  done
+       for i in $(cat /workspace/scan_id.txt); do gcloud artifacts docker images list-vulnerabilities $$i --location us \
+       --format='value(vulnerability.effectiveSeverity)' >> /workspace/list-vulnerabilities.txt;  done
+   - id: severity check
+     name: gcr.io/google.com/cloudsdktool/cloud-sdk
+     entrypoint: bash
+     waitFor: ['from to']
+     args:
+     - '-c'
+     - |-
+       if grep -Fxq $_SEVERITY /workspace/list-vulnerabilities.txt; then 
+          echo 'Failed vulnerability check' $$i
+          exit 1; 
+       else echo 'Passed with success on vulnerability check' $$i
+          exit 0; 
+       fi 
      env:
      - 'SEVERITY=$_SEVERITY'
      # Create release in Google Cloud Deploy
